apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blacklion-mssql-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: do-block-storage

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blacklion-mssql
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: blacklion-mssql
  template:
    metadata:
      labels:
        app: blacklion-mssql
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: blacklion-mssql
        image: mcr.microsoft.com/mssql/server:latest
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql
              key: SA_PASSWORD
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_PID
          value: "Developer"
        volumeMounts:
        - name: blacklion-mssqldb
          mountPath: /var/opt/mssql
      volumes:
      - name: blacklion-mssqldb
        persistentVolumeClaim:
          claimName: blacklion-mssql-data
---
apiVersion: v1
kind: Service
metadata:
  name: blacklion-mssql-service
spec:
  selector:
    app: blacklion-mssql
  ports:
  - protocol: TCP
    port: 1433
    targetPort: 1433
  type: LoadBalancer